### ISSUE TITLE
Method `request_project` takes over a minute to respond

### ISSUE THREAD

**Issue by shrnkld** [blocknetdx/eth-payment-processor#32] opened 2022-09-22 10:25 UTC
**Scenario:**

Trying to request a new XQuery project via curl, and using the method `request_project` is resulting in a delay of over a minute before any response.

**Steps to reproduce**
1. From a terminal/cli:
```curl http://194.163.143.68/xrs/projects \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","method":"request_project","params": [],"id":1}'
```

2. Wait...
3. Response takes >1 min

**To do:**
- [ ] Investigate the cause of the delay, which may be linked to this: https://github.com/blocknetdx/eth-payment-processor/issues/26
- [ ] fix to be discussed once the cause is confirmed

**Comment by shrnkld** [comment] 2022-09-22 14:11
**Update:**
I have now tested this call on another SNode and it repeatedly responds within a few seconds. I was unable to reproduce the issue on this newly deployed SNode.

**Comment by ConanMishler** [comment] 2022-10-13 05:22
Closing this issue because the delay was determined to be caused by the external ETH node referenced by my two SNodes being offline.

**Closed by ConanMishler** 2022-10-13 05:22 UTC
Labels: bug
